export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const SUBMENU_OPEN = 'SUBMENU_OPEN';
export const SUBMENU_CLOSE = 'SUBMENU_CLOSE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const TOGGLE_CART_ITEM_AMOUNT = 'TOGGLE_CART_ITEM_AMOUNT';
export const CLEAR_CART = 'CLEAR_CART';
export const COUNT_CART_TOTALS = 'COUNT_CART_TOTALS';

export const SET_LISTVIEW = 'SET_LISTVIEW';
export const SET_GRIDVIEW = 'SET_GRIDVIEW';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_UPDATE_CREDENTIALS_REQUEST =
  ' USER_UPDATE_CREDENTIALS_REQUEST';
export const USER_UPDATE_CREDENTIALS_SUCCESS =
  ' USER_UPDATE_CREDENTIALS_SUCCESS';
export const USER_UPDATE_CREDENTIALS_FAIL = ' USER_UPDATE_CREDENTIALS_FAIL';

export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST';
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';
export const USER_UPDATE_PASSWORD_FAIL = 'USER_UPDATE_PASSWORD_FAIL';

export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_SINGLE_PRODUCT_REQUEST = 'GET_SINGLE_PRODUCT_REQUEST';
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS';
export const GET_SINGLE_PRODUCT_FAIL = 'GET_SINGLE_PRODUCT_FAIL';

export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const UPDATE_SORT = 'UPDATE_SORT';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';

export const GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST';
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS';
export const GET_ALL_ORDERS_FAIL = 'GET_ALL_ORDERS_FAIL';

export const SHOW_USER_ORDERS_REQUEST = 'SHOW_USER_ORDERS_REQUEST';
export const SHOW_USER_ORDERS_SUCCESS = 'SHOW_USER_ORDERS_SUCCESS';
export const SHOW_USER_ORDERS_FAIL = 'SHOW_USER_ORDERS_FAIL';

export const SINGLE_ORDER_DETAILS_REQUEST = 'SINGLE_ORDER_DETAILS_REQUEST';
export const SINGLE_ORDER_DETAILS_SUCCESS = 'SINGLE_ORDER_DETAILS_SUCCESS';
export const SINGLE_ORDER_DETAILS_FAIL = 'SINGLE_ORDER_DETAILS_FAIL';
