const products = [
  {
    name: 'adidas Forum Exhibit low-top',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926604/my-ecommerce/BOTS/adidas_bots/kisspng-sneakers-adidas-shoe-nike-men-shoes-5acd226f9193e7.5012077515233931355963_s2ky0b.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4,
    numReviews: 11,
    price: 102,
    countInStock: 13,
    sizes: ['36', '36 2/3', '38', '39 1/3', '40', '40 2/3', '43 1/3'],
    colors: ['#000000', '#FF0000', '#00FFFF'],
    featured: false,
  },
  {
    name: 'adidas x Prada Luna Rossa',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/kisspng-bape-x-nmd-r1-adidas-nmd-r1-mens-sneakers-shoe-bape-x-adidas-nmdr1-unisex-green-camo-ba7326-sell-5b7001266f2a92.8233034515340669824554_roxp4i.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.7,
    numReviews: 7,
    price: 155,
    countInStock: 9,
    sizes: ['39 1/3', '41 1/3', '42', '42 2/3', '43 1/3'],
    colors: ['#000000', '#FFFFFF', '#00FFFF'],
    featured: false,
  },
  {
    name: 'adidas blanc low-top',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/kisspng-buy-adidas-nmd-r1-triple-black-2-17-kixify-marke-5baa1f4b6e3ae6.1667161815378757874515_wnqhnh.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.7,
    numReviews: 22,
    price: 155.99,
    countInStock: 11,
    sizes: ['36', '36 2/3', '39 1/3', '41 1/3', '43 1/3'],
    colors: ['#000000', '#C0C0C0'],
    featured: false,
  },
  {
    name: 'adidas zx 420',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/kisspng-adidas-adizero-adios-eu-39-13-adidas-womens-adiz-5b9e0e56dfd4c4.4047364515370850149168_eddh78.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.2,
    numReviews: 6,
    price: 49.99,
    countInStock: 11,
    sizes: ['36', '36 2/3', '42', '42 2/3', '43 1/3'],
    colors: ['#FFFF00', '#00FF00'],
    featured: false,
  },
  {
    name: 'adidas x craig green',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26566_fuuhwp.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.2,
    numReviews: 11,
    price: 79.99,
    countInStock: 9,
    sizes: ['36', '36 2/3', '38', '39 1/3', '40', '40 2/3', '41 1/3', '43 1/3'],
    colors: ['#FFFF00', '#808080'],
    featured: false,
  },
  {
    name: 'adidas nmd r1',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26565_effhqy.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.2,
    numReviews: 17,
    price: 109,
    countInStock: 21,
    sizes: ['36', '36 2/3', '38', '39 1/3', '40', '42', '43 1/3'],
    colors: ['#0000FF', '#FF8080'],
    featured: false,
  },
  {
    name: 'adidas x 424 arsenal',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26563_udcvn9.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.4,
    numReviews: 9,
    price: 121,
    countInStock: 7,
    sizes: ['36', '36 2/3', '37 1/3', '40', '40 2/3', '41 1/3', '42'],
    colors: ['#0000FF'],
    featured: false,
  },
  {
    name: 'adidas x 424 arsenal',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26562_qjk7t1.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.8,
    numReviews: 7,
    price: 69,
    countInStock: 7,
    sizes: ['37 1/3', '40', '40 2/3', '41 1/3', '42', '43 1/3'],
    colors: ['#0000FF', '#008000'],
    featured: false,
  },
  {
    name: 'adidas trx vintage',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26549_ngpj2y.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.3,
    numReviews: 8,
    price: 58,
    countInStock: 11,
    sizes: ['36', '37 1/3', '38', '39 1/3', '40', '41 1/3', '42'],
    colors: ['#FF0000', '#008000'],
    featured: false,
  },
  {
    name: 'adidas trx vintage',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26558_phmljx.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.7,
    numReviews: 23,
    price: 99,
    countInStock: 5,
    sizes: ['36', '37 1/3', '38', '41 1/3', '42'],
    colors: ['#000', '#fff'],
    featured: false,
  },
  {
    name: 'adidas wien low-top',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26556_k1xefj.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.4,
    numReviews: 17,
    price: 121,
    countInStock: 8,
    sizes: ['36', '38', '41 1/3', '42', '42 2/3', '43 1/3'],
    colors: ['#000', '#fff', '#008000'],
    featured: false,
  },
  {
    name: 'adidas x bunny',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26553_af8bz4.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.9,
    numReviews: 38,
    price: 119,
    countInStock: 6,
    sizes: ['36', '42', '42 2/3', '43 1/3'],
    colors: ['#000', '#0000ff'],
    featured: false,
  },
  {
    name: 'adidas forum buckle',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26553_af8bz4.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.6,
    numReviews: 26,
    price: 79,
    countInStock: 11,
    sizes: ['36', '39 1/3', '40', '42', '42 2/3', '43 1/3'],
    colors: ['#000', '#0000ff', '#FF00FF'],
    featured: false,
  },
  {
    name: 'adidas forum buckle',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26553_af8bz4.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.6,
    numReviews: 26,
    price: 79,
    countInStock: 11,
    sizes: ['36', '39 1/3', '40', '42', '42 2/3', '43 1/3'],
    colors: ['#000', '#0000ff', '#FF00FF'],
    featured: false,
  },
  {
    name: 'adidas forum buckle',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926604/my-ecommerce/BOTS/adidas_bots/kisspng-shoe-sneakers-adidas-mens-campus-women-adidas-sup-sneaker-baas-uk-campus-w-roze-5be1f55e354e83.3799856615415350702184_vrfwsx.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.2,
    numReviews: 13,
    price: 59,
    countInStock: 12,
    sizes: [
      '35.5',
      '36',
      '36 2/3',
      '38',
      '38 2/3',
      '39 1/3',
      '40 2/3',
      '42',
      '42 2/3',
      '44',
    ],
    colors: ['#FF0000', '#0000ff', '#FF00FF'],
    featured: false,
  },
  {
    name: 'adidas wien low-top',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926604/my-ecommerce/BOTS/adidas_bots/kisspng-sneakers-adidas-originals-superstar-girls-skate-sh-adidas-originals-superstar-girls-39-toddler-5b6e12d34ec647.7592615315339404353227_e8uald.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.4,
    numReviews: 14,
    price: 121,
    countInStock: 7,
    sizes: ['35.5', '36', '38', '38 2/3', '39 1/3', '40', '40 2/3', '42'],
    colors: ['#FFFFFF', '#FF00FF'],
    featured: false,
  },
  {
    name: 'adidas trx vintage',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926604/my-ecommerce/BOTS/adidas_bots/kisspng-nike-free-adidas-shoe-sneakers-hello-sports-5a88aede4ce563.937294001518907102315_xrnggv.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.7,
    numReviews: 11,
    price: 99,
    countInStock: 8,
    sizes: ['35.5', '36', '36 2/3', '37 1/3', '38 2/3', '40', '40 2/3', '42'],
    colors: ['#000', '#FF00FF'],
    featured: false,
  },
  {
    name: 'adidas x 424 arsenal',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926604/my-ecommerce/BOTS/adidas_bots/kisspng-mens-adidas-originals-nmd-r1-cardboard-trainers-5b9abc5ba51f58.0282181815368674196764_ljup0i.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.5,
    numReviews: 53,
    price: 49,
    countInStock: 22,
    sizes: [
      '35.5',
      '36',
      '37 1/3',
      '38',
      '38 2/3',
      '39 1/3',
      '40',
      '40 2/3',
      '42',
      '42 2/3',
      '44',
    ],
    colors: ['#000', '#FF00FF', '#fff'],
    featured: false,
  },
  {
    name: 'adidas blanc low-top',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/kisspng-adidas-shoe-sneakers-clip-art-women-shoes-5ab5851b7d1179.4244234315218455315123_viiegc.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.9,
    numReviews: 121,
    price: 76,
    countInStock: 13,
    sizes: ['35.5', '36', '38', '38 2/3', '40', '40 2/3', '42', '42 2/3', '44'],
    colors: ['#FF00FF', '#fff', '#800080	'],
    featured: false,
  },
  {
    name: 'adidas x Prada Luna Rossa',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/kisspng-adidas-nmd-r1-primeknit-mens-by1912-adidas-nmd-r1-5b9fdc66d3ee36.1366677715372033028681_gtisr1.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.7,
    numReviews: 22,
    price: 39,
    countInStock: 6,
    sizes: ['35.5', '36', '38 2/3', '40', '42'],
    colors: ['#fff'],
    featured: false,
  },
  {
    name: 'adidas x Prada Luna Rossa',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/kisspng-adidas-originals-swift-run-sports-shoes-adidas-tod-5ba1e0e730d5e0.2305695415373355272_d6klow.png',
    brand: 'adidas',
    category: 'children',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.6,
    numReviews: 22,
    price: 39,
    countInStock: 6,
    sizes: ['26.6', '27', '28', '29', '31', '33', '34'],
    colors: ['#FF00FF', '#FFF'],
    featured: false,
  },
  {
    name: 'adidas zx 420',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/kisspng-adidas-originals-skate-shoe-sneakers-adidas-adidas-shoes-5a7919d104d681.1072229915178859050198_lhb9kd.png',
    brand: 'adidas',
    category: 'children',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.2,
    numReviews: 17,
    price: 59,
    countInStock: 12,
    sizes: ['26.6', '27', '28', '29', '30', '31', '31.5', '33', '34'],
    colors: ['#FF00FF', '#FFF', '#00FF00', '#FF0000'],
    featured: false,
  },
  {
    name: 'adidas x 424 arsenal',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/kisspng-adidas-nmd-r1-primeknit-mens-by1912-adidas-nmd-r1-5b9fdc66d3ee36.1366677715372033028681_gtisr1.png',
    brand: 'adidas',
    category: 'children',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.5,
    numReviews: 7,
    price: 49,
    countInStock: 6,
    sizes: ['26.6', '27', '30', '31', '31.5'],
    colors: ['#FFF', '#00FF00'],
    featured: false,
  },
  {
    name: 'adidas wien low-top',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26546_xhkmom.png',
    brand: 'adidas',
    category: 'children',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.7,
    numReviews: 12,
    price: 78,
    countInStock: 6,
    sizes: ['27', , '29', '31', '32', '34'],
    colors: ['#FFF', '#00FF00'],
    featured: false,
  },
  {
    name: 'nike sportswear air',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926619/my-ecommerce/BOTS/nike_bots/pngegg_20_vihz6u.png',
    brand: 'nike',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.7,
    numReviews: 19,
    price: 59,
    countInStock: 11,
    sizes: ['36', '36 2/3', '38', '39 1/3', '40', '40 2/3', '42', '43 1/3'],
    colors: ['#0000FF', '#FFFFFF'],
    featured: false,
  },
  {
    name: 'nike waffle one',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926619/my-ecommerce/BOTS/nike_bots/pngegg_15_oimzfs.png',
    brand: 'nike',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.2,
    numReviews: 11,
    price: 79,
    countInStock: 17,
    sizes: ['36', '36 2/3', '38', '40', '40 2/3', '43 1/3'],
    colors: ['#000', '#FFFFFF'],
    featured: false,
  },
  {
    name: 'nike air force 1',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926619/my-ecommerce/BOTS/nike_bots/pngegg_11_ckti7t.png',
    brand: 'nike',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.8,
    numReviews: 9,
    price: 129,
    countInStock: 4,
    sizes: ['36', '40 2/3', '43 1/3'],
    colors: ['#FF0000'],
    featured: false,
  },
  {
    name: 'nike dunk',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926619/my-ecommerce/BOTS/nike_bots/pngegg_17_xka3kn.png',
    brand: 'nike',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.5,
    numReviews: 4,
    price: 179,
    countInStock: 19,
    sizes: ['36 2/3', '37 1/3', '38', '39 1/3', '40', '40 2/3', '41 1/3', '42'],
    colors: ['#C0C0C0', '#000000'],
    featured: false,
  },
  {
    name: 'nike air force luxe',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926619/my-ecommerce/BOTS/nike_bots/pngegg_13_njbwba.png',
    brand: 'nike',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.9,
    numReviews: 23,
    price: 89,
    countInStock: 9,
    sizes: ['36 2/3', '37 1/3', '40 2/3', '41 1/3', '42'],
    colors: ['#C0C0C0', '#000000', '#fff'],
    featured: false,
  },
  {
    name: 'nike af crater',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926618/my-ecommerce/BOTS/nike_bots/pngegg_5_uxa2ip.png',
    brand: 'nike',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.9,
    numReviews: 8,
    price: 39,
    countInStock: 13,
    sizes: ['36', '36 2/3', '38', '39 1/3', '40', '41 1/3', '42', '43 1/3'],
    colors: ['#0000FF', '#fff'],
    featured: false,
  },
  {
    nike: 'nike revolution',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926620/my-ecommerce/BOTS/nike_bots/pngegg_26_juigyp.png',
    brand: 'nike',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.2,
    numReviews: 17,
    price: 49,
    countInStock: 9,
    sizes: ['36', '37 1/3', '38', '39 1/3', '40', '40 2/3', '41 1/3', '42'],
    colors: ['#FF00FF', '#fff'],
    featured: false,
  },
  {
    name: 'nike blazer',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926620/my-ecommerce/BOTS/nike_bots/pngegg_29_kfnw8x.png',
    brand: 'nike',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.8,
    numReviews: 33,
    price: 79,
    countInStock: 11,
    sizes: ['35.5', '36', '37 1/3', '40', '40 2/3', '41 1/3', '42'],
    colors: ['#FF00FF', '#fff', '#C0C0C0'],
    featured: false,
  },
  {
    name: 'nike pixel',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926620/my-ecommerce/BOTS/nike_bots/pngegg_27_wepoyt.png',
    brand: 'nike',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.6,
    numReviews: 41,
    price: 39,
    countInStock: 4,
    sizes: ['35.5', '36', '40', '40 2/3'],
    colors: ['#FF00FF', '#fff'],
    featured: false,
  },
  {
    name: 'nike air max bolt',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926620/my-ecommerce/BOTS/nike_bots/pngegg_25_mi7vo8.png',
    brand: 'nike',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.9,
    numReviews: 17,
    price: 83,
    countInStock: 7,
    sizes: ['35.5', '36', '38', '38 2/3', '40 2/3', '41 1/3', '42'],
    colors: ['#FF00FF'],
    featured: false,
  },
  {
    name: 'nike af crater',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926619/my-ecommerce/BOTS/nike_bots/pngegg_21_d7qsr1.png',
    brand: 'nike',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.8,
    numReviews: 8,
    price: 45,
    countInStock: 5,
    sizes: ['35.5', '36', '38', '41 1/3', '42'],
    colors: ['#C0C0C0'],
    featured: false,
  },
  {
    name: 'nike air force luxe',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926618/my-ecommerce/BOTS/nike_bots/new1_ydrjyz.png',
    brand: 'nike',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.8,
    numReviews: 21,
    price: 129,
    countInStock: 15,
    sizes: [
      '35.5',
      '36 2/3',
      '38',
      '38 2/3',
      '39 1/3',
      '40',
      '40 2/3',
      '41 1/3',
      '42',
      '42 2/3',
      '44',
    ],
    colors: ['#FF00FF', '#FF0000'],
    featured: false,
  },
  {
    name: 'nike dunk',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926618/my-ecommerce/BOTS/nike_bots/new3_n8cvjt.png',
    brand: 'nike',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.4,
    numReviews: 14,
    price: 89,
    countInStock: 12,
    sizes: ['36 2/3', '38', '38 2/3', '39 1/3', '42', '42 2/3', '44'],
    colors: ['#FF00FF', '#FF0000', '#FFFFFF'],
    featured: false,
  },
  {
    name: 'nike air force 1',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926618/my-ecommerce/BOTS/nike_bots/new4_zvzcm9.png',
    brand: 'nike',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.7,
    numReviews: 44,
    price: 99,
    countInStock: 22,
    sizes: [
      '35.5',
      '36',
      '38',
      '38 2/3',
      '39 1/3',
      '40',
      '40 2/3',
      '41 1/3',
      '42',
      '42 2/3',
      '44',
    ],
    colors: ['#FF00FF', '#800080', '#FFFFFF'],
    featured: false,
  },
  {
    name: 'nike sportswear air',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926618/my-ecommerce/BOTS/nike_bots/new2_bqynbl.png',
    brand: 'nike',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.3,
    numReviews: 24,
    price: 69,
    countInStock: 13,
    sizes: ['35.5', '36', '38', '39 1/3', '40', '41 1/3', '42', '44'],
    colors: ['#FF00FF', '#FFFF00'],
    featured: false,
  },
  {
    name: 'nike waffle one',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926619/my-ecommerce/BOTS/nike_bots/pngegg_24_kphbjb.png',
    brand: 'nike',
    category: 'children',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 78,
    price: 49,
    countInStock: 13,
    sizes: ['26.6', '27', '27.5', '28', '30', '31.5', '32', '34'],
    colors: ['#000'],
    featured: false,
  },
  {
    name: 'nike dunk',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926619/my-ecommerce/BOTS/nike_bots/pngegg_23_paglko.png',
    brand: 'nike',
    category: 'children',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.5,
    numReviews: 18,
    price: 29,
    countInStock: 8,
    sizes: ['26.6', '27', '27.5', '28', '32', '34'],
    colors: ['#FF00FF', '#00FFFF'],
    featured: false,
  },
  {
    name: 'nike air max bolt',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926620/my-ecommerce/BOTS/nike_bots/pngegg_27_wepoyt.png',
    brand: 'nike',
    category: 'children',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.6,
    numReviews: 44,
    price: 49,
    countInStock: 11,
    sizes: ['26.6', '27', '27.5', '28', '29', '31.5', '33', '34'],
    colors: ['#FF00FF', '#fff'],
    featured: false,
  },
  {
    name: 'puma carina mid',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926632/my-ecommerce/BOTS/puma_bots/pngegg_10_cn9ou6.png',
    brand: 'puma',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.6,
    numReviews: 44,
    price: 99,
    countInStock: 11,
    sizes: ['36', '36 2/3', '38', '39 1/3', '40', '41 1/3', '42', '43 1/3'],
    colors: ['#ff0000', '#fff'],
    featured: false,
  },
  {
    name: 'puma rebound',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926632/my-ecommerce/BOTS/puma_bots/pngegg_39_tdvfoy.png',
    brand: 'puma',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.2,
    numReviews: 12,
    price: 79,
    countInStock: 13,
    sizes: ['36', '36 2/3', '40', '41 1/3', '42', '43 1/3'],
    colors: ['#FFFF00'],
    featured: false,
  },
  {
    name: 'puma cali',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926632/my-ecommerce/BOTS/puma_bots/pngegg_18_vcllex.png',
    brand: 'puma',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.6,
    numReviews: 22,
    price: 49,
    countInStock: 16,
    sizes: ['36', '39 1/3', '40', '40 2/3', '42', '42 2/3'],
    colors: ['#000'],
    featured: false,
  },
  {
    name: 'puma cilia',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926632/my-ecommerce/BOTS/puma_bots/pngegg_15_cg7ibd.png',
    brand: 'puma',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4,
    numReviews: 7,
    price: 59,
    countInStock: 13,
    sizes: ['36', '39 1/3', '40', '42 2/3'],
    colors: ['#C0C0C0'],
    featured: false,
  },
  {
    name: 'puma cali wedge',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926632/my-ecommerce/BOTS/puma_bots/pngegg_13_r50ywj.png',
    brand: 'puma',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.5,
    numReviews: 22,
    price: 67,
    countInStock: 6,
    sizes: ['36', '39 1/3', '40'],
    colors: ['#FF0000'],
    featured: false,
  },
  {
    name: 'puma pure',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926631/my-ecommerce/BOTS/puma_bots/pngegg_3_g30ikx.png',
    brand: 'puma',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.4,
    numReviews: 13,
    price: 56,
    countInStock: 11,
    sizes: ['36', '36 2/3', '38', '39 1/3', '40', '40 2/3', '41 1/3', '42'],
    colors: ['#00FF00'],
    featured: false,
  },
  {
    name: 'puma ca pro',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926631/my-ecommerce/BOTS/puma_bots/pngegg_4_tpzuir.png',
    brand: 'puma',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.6,
    numReviews: 33,
    price: 49,
    countInStock: 22,
    sizes: ['36', '38', '39 1/3', '40', '40 2/3', '41 1/3', '42'],
    colors: ['#000', '#fff'],
    featured: false,
  },
  {
    name: 'puma roma',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926631/my-ecommerce/BOTS/puma_bots/pngegg_2_wrnjpo.png',
    brand: 'puma',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.2,
    numReviews: 26,
    price: 69,
    countInStock: 11,
    sizes: ['36', '38', '39 1/3', '40', '40 2/3'],
    colors: ['#000', '#fff'],
    featured: false,
  },
  {
    name: 'puma shuffle',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926631/my-ecommerce/BOTS/puma_bots/pngegg_9_e6bair.png',
    brand: 'puma',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 7,
    price: 119,
    countInStock: 18,
    sizes: ['36', '37 1/3', '38', '39 1/3', '40', '40 2/3', '41 1/3', '42'],
    colors: ['#000', '#808080'],
    featured: false,
  },
  {
    name: 'puma rebound',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926631/my-ecommerce/BOTS/puma_bots/pngegg_1_tm6v92.png',
    brand: 'puma',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 17,
    price: 179,
    countInStock: 12,
    sizes: ['36', '38', '39 1/3', '40 2/3', '41 1/3', '42'],
    colors: ['#000', '#fff'],
    featured: false,
  },
  {
    name: 'puma shuffle',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926632/my-ecommerce/BOTS/puma_bots/pngegg_16_jmwc7z.png',
    brand: 'puma',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.5,
    numReviews: 11,
    price: 49,
    countInStock: 12,
    sizes: [
      '36',
      '36 2/3',
      '37 1/3',
      '38',
      '38 2/3',
      '39 1/3',
      '40',
      '42',
      '42 2/3',
      '44',
    ],
    colors: ['#FF00FF', '#fff'],
    featured: false,
  },
  {
    name: 'puma roma',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926632/my-ecommerce/BOTS/puma_bots/pngegg_13_r50ywj.png',
    brand: 'puma',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.7,
    numReviews: 12,
    price: 79,
    countInStock: 11,
    sizes: ['36', '36 2/3', '38', '38 2/3', '39 1/3', '40', '42'],
    colors: ['#FF0000', '#fff'],
    featured: false,
  },
  {
    name: 'puma rebound',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926631/my-ecommerce/BOTS/puma_bots/pngegg_5_oku0jm.png',
    brand: 'puma',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 26,
    price: 109,
    countInStock: 17,
    sizes: ['35.5', '36', '36 2/3', '38', '38 2/3', '39 1/3', '40'],
    colors: ['#FF00FF', '#fff'],
    featured: false,
  },
  {
    name: 'puma cali wedge',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926631/my-ecommerce/BOTS/puma_bots/pngegg_3_g30ikx.png',
    brand: 'puma',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.3,
    numReviews: 15,
    price: 49,
    countInStock: 11,
    sizes: [
      '35.5',
      '36',
      '36 2/3',
      '39 1/3',
      '40 2/3',
      '41 1/3',
      '42 2/3',
      '43 1/3',
      '44',
    ],
    colors: ['#008000'],
    featured: false,
  },
  {
    name: 'puma cali',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926633/my-ecommerce/BOTS/puma_bots/pngegg_fuhn1q.png',
    brand: 'puma',
    category: 'children',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.3,
    numReviews: 15,
    price: 49,
    countInStock: 11,
    sizes: ['26.6', '27.5', '28', '29', '31', '31.5', '32', '33'],
    colors: ['#C0C0C0', '#000000'],
    featured: false,
  },
  {
    name: 'puma roma',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926632/my-ecommerce/BOTS/puma_bots/pngegg_22_mdwpsx.png',
    brand: 'puma',
    category: 'children',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.6,
    numReviews: 26,
    price: 39,
    countInStock: 13,
    sizes: ['26.6', '27.5', '31', '31.5', '32', '33'],
    colors: ['#0000FF'],
    featured: false,
  },
  {
    name: 'puma cali wedge',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926632/my-ecommerce/BOTS/puma_bots/pngegg_16_jmwc7z.png',
    brand: 'puma',
    category: 'children',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.4,
    numReviews: 11,
    price: 59,
    countInStock: 13,
    sizes: ['27', '28', '29', '30', '31', '31.5', '34'],
    colors: ['#FF00FF'],
    featured: false,
  },
  {
    name: 'puma shuffle',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926632/my-ecommerce/BOTS/puma_bots/pngegg_17_bli9ns.png',
    brand: 'puma',
    category: 'children',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 17,
    price: 79,
    countInStock: 13,
    sizes: ['27', '28', '29', '30', '34'],
    colors: ['#000'],
    featured: false,
  },
  {
    name: 'adidas x Prada Luna Rossa',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926789/my-ecommerce/OUTDOOR/adidas_outdoor/kisspng-sports-shoes-trail-running-gore-tex-5b9edfd56f0364.3693465715371386454547_kr0w7n.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'outdoor',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 17,
    price: 159,
    countInStock: 13,
    sizes: ['36', '37 1/3', '38', '39 1/3', '40', '42', '42 2/3', '43 1/3'],
    colors: ['#000'],
    featured: false,
  },
  {
    name: 'adidas zx 420',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926789/my-ecommerce/OUTDOOR/adidas_outdoor/kisspng-sneakers-shoe-hiking-boot-adidas-gore-tex-5b0be6f465edc7.2138912715275066764175_ua6ots.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'outdoor',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.5,
    numReviews: 8,
    price: 79,
    countInStock: 7,
    sizes: ['36', '42', '42 2/3', '43 1/3'],
    colors: ['#000'],
    featured: false,
  },
  {
    name: 'adidas forum buckle',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926788/my-ecommerce/OUTDOOR/adidas_outdoor/adidas-shoes-png-26571_yffvuh.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'outdoor',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 28,
    price: 99,
    countInStock: 17,
    sizes: ['36', '36 2/3', '37 1/3', '38', '39 1/3', '40', '41 1/3', '42'],
    colors: ['#fff', '#000'],
    featured: false,
  },
  {
    name: 'adidas trx vintage',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926788/my-ecommerce/OUTDOOR/adidas_outdoor/kisspng-hiking-boot-shoe-jack-wolfskin-footwear-5af68fac37b4f5.7431052715261080762282_ropoat.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'outdoor',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.8,
    numReviews: 11,
    price: 129,
    countInStock: 13,
    sizes: ['36', '38', '39 1/3', '40', '41 1/3', '42'],
    colors: ['#C0C0C0'],
    featured: false,
  },
  {
    name: 'adidas trx vintage',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926789/my-ecommerce/OUTDOOR/adidas_outdoor/kisspng-sports-shoes-adidas-ultra-boost-mens-running-shoe-5b9b8c9ce4d6b8.6365096915369207329373_obbsqk.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'outdoor',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 19,
    price: 89,
    countInStock: 13,
    sizes: [
      '35.5',
      '36',
      '37 1/3',
      '38',
      '40',
      '40 2/3',
      '41 1/3',
      '42',
      '42 2/3',
      '43 1/3',
      '44',
    ],
    colors: ['#0000FF', '#00FFFF'],
    featured: false,
  },
  {
    name: 'adidas x craig green',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926788/my-ecommerce/OUTDOOR/adidas_outdoor/kisspng-shoe-quechua-bidezidor-kirol-sneakers-decathlon-gr-hiking-shoes-5aa76e81805c60.6147768815209222415258_lpje8e.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'outdoor',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.6,
    numReviews: 11,
    price: 69,
    countInStock: 11,
    sizes: ['35.5', '36', '38', '40', '40 2/3', '42', '42 2/3', '43 1/3', '44'],
    colors: ['#FF00FF', '#fff'],
    featured: false,
  },
  {
    name: 'adidas x Prada Luna Rossa',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926788/my-ecommerce/OUTDOOR/adidas_outdoor/adidas-shoes-png-26551_ndwidx.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'outdoor',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.9,
    numReviews: 13,
    price: 118,
    countInStock: 17,
    sizes: ['35.5', '36', '38', '40', '40 2/3', '42', '42 2/3', '43 1/3', '44'],
    colors: ['#FF0000'],
    featured: false,
  },
  {
    name: 'nike sportswear air',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926789/my-ecommerce/OUTDOOR/nike_outdoor/pngegg_3_bbao1z.png',
    brand: 'nike',
    category: 'men',
    subCategory: 'outdoor',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.9,
    numReviews: 13,
    price: 118,
    countInStock: 17,
    sizes: ['36', '36 2/3', '37 1/3', '40', '40 2/3', '41 1/3', '42', '42 2/3'],
    colors: ['#0000FF'],
    featured: false,
  },
  {
    name: 'nike pixel',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926789/my-ecommerce/OUTDOOR/nike_outdoor/pngegg_10_o7afde.png',
    brand: 'nike',
    category: 'men',
    subCategory: 'outdoor',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.4,
    numReviews: 11,
    price: 79,
    countInStock: 11,
    sizes: ['36 2/3', '37 1/3', '40', '40 2/3', '41 1/3', '42'],
    colors: ['#0000FF'],
    featured: false,
  },
  {
    name: 'nike blazer',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926789/my-ecommerce/OUTDOOR/nike_outdoor/pngegg_1_i9nplf.png',
    brand: 'nike',
    category: 'men',
    subCategory: 'outdoor',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.8,
    numReviews: 18,
    price: 79,
    countInStock: 11,
    sizes: ['36 2/3', '40 2/3', '41 1/3', '42'],
    colors: ['#FF0000'],
    featured: false,
  },
  {
    nike: 'nike revolution',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926789/my-ecommerce/OUTDOOR/nike_outdoor/pngegg_2_biiuvl.png',
    brand: 'nike',
    category: 'women',
    subCategory: 'outdoor',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 26,
    price: 69,
    countInStock: 11,
    sizes: [
      '35.5',
      '36 2/3',
      '38',
      '39 1/3',
      '40',
      '40 2/3',
      '41 1/3',
      '42',
      '42 2/3',
      '44',
    ],
    colors: ['#0000FF', '#000000', '#C0C0C0'],
    featured: false,
  },
  {
    name: 'puma rebound',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926790/my-ecommerce/OUTDOOR/puma_outdoor/pngegg_zloxgt.png',
    brand: 'puma',
    category: 'men',
    subCategory: 'outdoor',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 52,
    price: 119,
    countInStock: 18,
    sizes: [
      '36',
      '36 2/3',
      '37 1/3',
      '38',
      '40',
      '40 2/3',
      '41 1/3',
      '42',
      '42 2/3',
    ],
    colors: ['#fff'],
    featured: false,
  },
  {
    name: 'puma cali wedge',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926789/my-ecommerce/OUTDOOR/puma_outdoor/pngegg_1_z4n6ml.png',
    brand: 'puma',
    category: 'men',
    subCategory: 'outdoor',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.8,
    numReviews: 15,
    price: 89,
    countInStock: 7,
    sizes: ['37 1/3', '38', '40', '40 2/3', '41 1/3'],
    colors: ['#808080'],
    featured: false,
  },
  {
    name: 'puma roma',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926790/my-ecommerce/OUTDOOR/puma_outdoor/pngegg_2_iqtqp6.png',
    brand: 'puma',
    category: 'men',
    subCategory: 'outdoor',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.6,
    numReviews: 23,
    price: 99,
    countInStock: 11,
    sizes: [
      '36',
      '36 2/3',
      '39 1/3',
      '40',
      '40 2/3',
      '41 1/3',
      '42 2/3',
      '43 1/3',
    ],
    colors: ['#0000FF', '#fff', '#00FFFF'],
    featured: false,
  },
  {
    name: 'puma pure',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926790/my-ecommerce/OUTDOOR/puma_outdoor/pngegg_3_dsoiji.png',
    brand: 'puma',
    category: 'women',
    subCategory: 'outdoor',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 12,
    price: 64,
    countInStock: 21,
    sizes: [
      '36',
      '37 1/3',
      '38',
      '39 1/3',
      '40',
      '40 2/3',
      '41 1/3',
      '42',
      '42 2/3',
    ],
    colors: ['#0000FF', '#fff'],
    featured: false,
  },
  {
    name: 'puma carina mid',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926790/my-ecommerce/OUTDOOR/puma_outdoor/pngegg_4_hbavtt.png',
    brand: 'puma',
    category: 'women',
    subCategory: 'outdoor',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.2,
    numReviews: 23,
    price: 79,
    countInStock: 11,
    sizes: ['36', '37 1/3', '38', '39 1/3', '40 2/3', '41 1/3', '42'],
    colors: ['#FF00FF', '#00FFFF'],
    featured: false,
  },

  {
    name: 'adidas wien',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926800/my-ecommerce/SANDALS/adidas_sandals/kisspng-sandal-adidas-originals-shoe-adidas-yeezy-flip-flop-5aeb628a0e8321.5256508615253756260595_hugbjf.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.4,
    numReviews: 17,
    price: 44,
    countInStock: 12,
    sizes: ['36', '39 1/3', '40', '41 1/3', '42', '43 1/3'],
    colors: ['#FFFF00', '#000'],
    featured: false,
  },
  {
    name: 'adidas trx vintage',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926800/my-ecommerce/SANDALS/adidas_sandals/kisspng-slipper-adidas-sandals-instiz-shoe-adidas-originals-5b3cebd63e5483.3833016115307191902553_kzkqqp.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.6,
    numReviews: 9,
    price: 39,
    countInStock: 22,
    sizes: [
      '36',
      '36 2/3',
      '37 1/3',
      '38',
      '39 1/3',
      '40',
      '40 2/3',
      '42',
      '43 1/3',
    ],
    colors: ['#008000'],
    featured: false,
  },
  {
    name: 'adidas x 424 arsenal',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926799/my-ecommerce/SANDALS/adidas_sandals/kisspng-slide-adidas-sandals-flip-flops-flip-flop-5b20bd6b85db05.5980508115288722995483_blsvd9.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 27,
    price: 39,
    countInStock: 11,
    sizes: ['36', '37 1/3', '39 1/3', '40', '40 2/3', '42'],
    colors: ['#000'],
    featured: false,
  },
  {
    name: 'adidas x Prada Luna Rossa',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926799/my-ecommerce/SANDALS/adidas_sandals/kisspng-chaco-shoe-adidas-sandals-sneakers-chaco-5b2ddefbd4a493.846642281529732859871_eb0kr1.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.8,
    numReviews: 11,
    price: 34,
    countInStock: 7,
    sizes: ['36', '37 1/3', '39 1/3', '40'],
    colors: ['#808080'],
    featured: false,
  },
  {
    name: 'adidas forum buckle',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926801/my-ecommerce/SANDALS/adidas_sandals/pngegg_3_zbvp3a.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.2,
    numReviews: 23,
    price: 39,
    countInStock: 11,
    sizes: ['35.5', '36', '36 2/3', '38 2/3', '39 1/3', '42 2/3', '44'],
    colors: ['#FF00FF', '#000'],
    featured: false,
  },
  {
    name: 'adidas Forum Exhibit',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926799/my-ecommerce/SANDALS/adidas_sandals/kisspng-slipper-adidas-sandals-flip-flops-slide-puma-und-adidas-5b4afad3b862d0.1855739415316405317553_noucmk.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 45,
    price: 39,
    countInStock: 11,
    sizes: [
      '35.5',
      '36 2/3',
      '38',
      '38 2/3',
      '39 1/3',
      '40',
      '41 1/3',
      '42',
      '42 2/3',
      '43 1/3',
      '44',
    ],
    colors: ['#0000FF', '#000'],
    featured: false,
  },
  {
    name: 'nike waffle one',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926800/my-ecommerce/SANDALS/nike_sandals/pngegg_akm2vc.png',
    brand: 'nike',
    category: 'men',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.8,
    numReviews: 18,
    price: 39,
    countInStock: 12,
    sizes: ['36', '38', '39 1/3', '40', '40 2/3', '41 1/3', '42'],
    colors: ['#fff', '#000'],
    featured: false,
  },
  {
    name: 'nike air force luxe',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926800/my-ecommerce/SANDALS/nike_sandals/pngegg_3_ey1qnw.png',
    brand: 'nike',
    category: 'men',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.2,
    numReviews: 7,
    price: 34,
    countInStock: 12,
    sizes: ['36', '40', '40 2/3', '41 1/3', '42'],
    colors: ['#fff'],
    featured: false,
  },
  {
    name: 'nike air max bolt',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926800/my-ecommerce/SANDALS/nike_sandals/pngegg_1_oaub3z.png',
    brand: 'nike',
    category: 'men',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.6,
    numReviews: 16,
    price: 39,
    countInStock: 18,
    sizes: ['36', '36 2/3', '37 1/3', '38', '39 1/3', '40 2/3', '41 1/3', '42'],
    colors: ['#000'],
    featured: false,
  },
  {
    name: 'nike blazer',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926799/my-ecommerce/SANDALS/nike_sandals/pngegg_14_ihrh60.png',
    brand: 'nike',
    category: 'men',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 34,
    price: 36,
    countInStock: 18,
    sizes: ['36', '36 2/3', '37 1/3', '38', '39 1/3', '40 2/3'],
    colors: ['#fff', '#808080'],
    featured: false,
  },
  {
    nike: 'nike revolution',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926800/my-ecommerce/SANDALS/nike_sandals/pngegg_2_tds3ho.png',
    brand: 'nike',
    category: 'women',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 43,
    price: 39,
    countInStock: 18,
    sizes: [
      '35.5',
      '36',
      '37 1/3',
      '38',
      '38 2/3',
      '39 1/3',
      '40',
      '40 2/3',
      '41 1/3',
      '44',
    ],
    colors: ['#FF00FF', '#000'],
    featured: false,
  },
  {
    name: 'nike af crater',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926800/my-ecommerce/SANDALS/nike_sandals/pngegg_5_a2bjd2.png',
    brand: 'nike',
    category: 'women',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.3,
    numReviews: 11,
    price: 59,
    countInStock: 6,
    sizes: ['37 1/3', '38', '38 2/3', '39 1/3', '40'],
    colors: ['#FF0000'],
    featured: false,
  },
  {
    name: 'nike waffle one',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926799/my-ecommerce/SANDALS/nike_sandals/pngegg_4_pdqkjl.png',
    brand: 'nike',
    category: 'women',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.6,
    numReviews: 31,
    price: 37,
    countInStock: 16,
    sizes: [
      '35.5',
      '37 1/3',
      '38',
      '38 2/3',
      '39 1/3',
      '40',
      '40 2/3',
      '41 1/3',
      '42',
    ],
    colors: ['#000'],
    featured: false,
  },
  {
    name: 'puma shuffle',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926801/my-ecommerce/SANDALS/puma_sandals/pngegg_eb1aep.png',
    brand: 'puma',
    category: 'men',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 23,
    price: 42,
    countInStock: 16,
    sizes: ['36', '37 1/3', '38', '39 1/3', '40 2/3', '41 1/3', '42', '42 2/3'],
    colors: ['#000'],
    featured: false,
  },
  {
    name: 'puma cali wedge',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926800/my-ecommerce/SANDALS/puma_sandals/pngegg_1_b8or6g.png',
    brand: 'puma',
    category: 'men',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.9,
    numReviews: 11,
    price: 48,
    countInStock: 11,
    sizes: ['36', '38', '39 1/3', '40 2/3', '41 1/3'],
    colors: ['#000'],
    featured: false,
  },
  {
    name: 'puma shuffle',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926801/my-ecommerce/SANDALS/puma_sandals/pngegg_2_vrikwp.png',
    brand: 'puma',
    category: 'women',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.7,
    numReviews: 20,
    price: 39,
    countInStock: 12,
    sizes: [
      '36',
      '36 2/3',
      '38',
      '38 2/3',
      '39 1/3',
      '40',
      '40 2/3',
      '41 1/3',
      '42',
      '42 2/3',
    ],
    colors: ['#FFFF00', '#fff'],
    featured: false,
  },
  {
    name: 'puma ca pro',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926801/my-ecommerce/SANDALS/puma_sandals/pngegg_21_wjzcu7.png',
    brand: 'puma',
    category: 'women',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.1,
    numReviews: 14,
    price: 47,
    countInStock: 7,
    sizes: ['36 2/3', '38', '38 2/3', '39 1/3', '40', '42', '42 2/3'],
    colors: ['#800000'],
    featured: false,
  },
  {
    name: 'puma cali wedge',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926800/my-ecommerce/SANDALS/puma_sandals/pngegg_3_ry8wlb.png',
    brand: 'puma',
    category: 'women',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.7,
    numReviews: 22,
    price: 42,
    countInStock: 7,
    sizes: ['36 2/3', '38', '38 2/3', '39 1/3', '40'],
    colors: ['#0000FF'],
    featured: false,
  },
  {
    name: 'puma rebound',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926799/my-ecommerce/SANDALS/puma_sandals/pngegg_19_j0sdgy.png',
    brand: 'puma',
    category: 'women',
    subCategory: 'sandals',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 5,
    numReviews: 74,
    price: 49.99,
    countInStock: 7,
    sizes: [
      '36',
      '36 2/3',
      '38',
      '38 2/3',
      '39 1/3',
      '40',
      '40 2/3',
      '41 1/3',
      '42',
      '42 2/3',
    ],
    colors: ['#FF00FF', '#FFFFFF', '#00FFFF'],
    featured: false,
  },
];
