const products = [
  {
    name: 'adidas Forum Exhibit low-top',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926604/my-ecommerce/BOTS/adidas_bots/kisspng-sneakers-adidas-shoe-nike-men-shoes-5acd226f9193e7.5012077515233931355963_s2ky0b.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4,
    numReviews: 11,
    price: 102,
    countInStock: 13,
    sizes: ['36', '36 2/3', '38', '39 1/3', '40', '40 2/3', '43 1/3'],
    colors: ['#000000', '#FF0000', '#00FFFF'],
    featured: false,
  },
  {
    name: 'adidas x Prada Luna Rossa',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/kisspng-bape-x-nmd-r1-adidas-nmd-r1-mens-sneakers-shoe-bape-x-adidas-nmdr1-unisex-green-camo-ba7326-sell-5b7001266f2a92.8233034515340669824554_roxp4i.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.7,
    numReviews: 7,
    price: 155,
    countInStock: 9,
    sizes: ['39 1/3', '41 1/3', '42', '42 2/3', '43 1/3'],
    colors: ['#000000', '#FFFFFF', '#00FFFF'],
    featured: false,
  },
  {
    name: 'adidas blanc low-top',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/kisspng-buy-adidas-nmd-r1-triple-black-2-17-kixify-marke-5baa1f4b6e3ae6.1667161815378757874515_wnqhnh.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.7,
    numReviews: 22,
    price: 155.99,
    countInStock: 11,
    sizes: ['36', '36 2/3', '39 1/3', '41 1/3', '43 1/3'],
    colors: ['#000000', '#C0C0C0'],
    featured: false,
  },
  {
    name: 'adidas zx 420',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/kisspng-adidas-adizero-adios-eu-39-13-adidas-womens-adiz-5b9e0e56dfd4c4.4047364515370850149168_eddh78.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.2,
    numReviews: 6,
    price: 49.99,
    countInStock: 11,
    sizes: ['36', '36 2/3', '42', '42 2/3', '43 1/3'],
    colors: ['#FFFF00', '#00FF00'],
    featured: false,
  },
  {
    name: 'adidas x craig green',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26566_fuuhwp.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.2,
    numReviews: 11,
    price: 79.99,
    countInStock: 9,
    sizes: ['36', '36 2/3', '38', '39 1/3', '40', '40 2/3', '41 1/3', '43 1/3'],
    colors: ['#FFFF00', '#808080'],
    featured: false,
  },
  {
    name: 'adidas nmd r1',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26565_effhqy.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.2,
    numReviews: 17,
    price: 109,
    countInStock: 21,
    sizes: ['36', '36 2/3', '38', '39 1/3', '40', '42', '43 1/3'],
    colors: ['#0000FF', '#FF8080'],
    featured: false,
  },
  {
    name: 'adidas x 424 arsenal',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26563_udcvn9.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.4,
    numReviews: 9,
    price: 121,
    countInStock: 7,
    sizes: ['36', '36 2/3', '37 1/3', '40', '40 2/3', '41 1/3', '42'],
    colors: ['#0000FF'],
    featured: false,
  },
  {
    name: 'adidas x 424 arsenal',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26562_qjk7t1.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.8,
    numReviews: 7,
    price: 69,
    countInStock: 7,
    sizes: ['37 1/3', '40', '40 2/3', '41 1/3', '42', '43 1/3'],
    colors: ['#0000FF', '#008000'],
    featured: false,
  },
  {
    name: 'adidas trx vintage',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26549_ngpj2y.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.3,
    numReviews: 8,
    price: 58,
    countInStock: 11,
    sizes: ['36', '37 1/3', '38', '39 1/3', '40', '41 1/3', '42'],
    colors: ['#FF0000', '#008000'],
    featured: false,
  },
  {
    name: 'adidas trx vintage',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26558_phmljx.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.7,
    numReviews: 23,
    price: 99,
    countInStock: 5,
    sizes: ['36', '37 1/3', '38', '41 1/3', '42'],
    colors: ['#000', '#fff'],
    featured: false,
  },
  {
    name: 'adidas wien low-top',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26556_k1xefj.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.4,
    numReviews: 17,
    price: 121,
    countInStock: 8,
    sizes: ['36', '38', '41 1/3', '42', '42 2/3', '43 1/3'],
    colors: ['#000', '#fff', '#008000'],
    featured: false,
  },
  {
    name: 'adidas x bunny',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26553_af8bz4.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.9,
    numReviews: 38,
    price: 119,
    countInStock: 6,
    sizes: ['36', '42', '42 2/3', '43 1/3'],
    colors: ['#000', '#0000ff'],
    featured: false,
  },
  {
    name: 'adidas forum buckle',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26553_af8bz4.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.6,
    numReviews: 26,
    price: 79,
    countInStock: 11,
    sizes: ['36', '39 1/3', '40', '42', '42 2/3', '43 1/3'],
    colors: ['#000', '#0000ff', '#FF00FF'],
    featured: false,
  },
  {
    name: 'adidas forum buckle',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26553_af8bz4.png',
    brand: 'adidas',
    category: 'men',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.6,
    numReviews: 26,
    price: 79,
    countInStock: 11,
    sizes: ['36', '39 1/3', '40', '42', '42 2/3', '43 1/3'],
    colors: ['#000', '#0000ff', '#FF00FF'],
    featured: false,
  },
  {
    name: 'adidas forum buckle',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926604/my-ecommerce/BOTS/adidas_bots/kisspng-shoe-sneakers-adidas-mens-campus-women-adidas-sup-sneaker-baas-uk-campus-w-roze-5be1f55e354e83.3799856615415350702184_vrfwsx.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.2,
    numReviews: 13,
    price: 59,
    countInStock: 12,
    sizes: [
      '35.5',
      '36',
      '36 2/3',
      '38',
      '38 2/3',
      '39 1/3',
      '40 2/3',
      '42',
      '42 2/3',
      '44',
    ],
    colors: ['#FF0000', '#0000ff', '#FF00FF'],
    featured: false,
  },
  {
    name: 'adidas wien low-top',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926604/my-ecommerce/BOTS/adidas_bots/kisspng-sneakers-adidas-originals-superstar-girls-skate-sh-adidas-originals-superstar-girls-39-toddler-5b6e12d34ec647.7592615315339404353227_e8uald.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.4,
    numReviews: 14,
    price: 121,
    countInStock: 7,
    sizes: ['35.5', '36', '38', '38 2/3', '39 1/3', '40', '40 2/3', '42'],
    colors: ['#FFFFFF', '#FF00FF'],
    featured: false,
  },
  {
    name: 'adidas trx vintage',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926604/my-ecommerce/BOTS/adidas_bots/kisspng-nike-free-adidas-shoe-sneakers-hello-sports-5a88aede4ce563.937294001518907102315_xrnggv.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.7,
    numReviews: 11,
    price: 99,
    countInStock: 8,
    sizes: ['35.5', '36', '36 2/3', '37 1/3', '38 2/3', '40', '40 2/3', '42'],
    colors: ['#000', '#FF00FF'],
    featured: false,
  },
  {
    name: 'adidas x 424 arsenal',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926604/my-ecommerce/BOTS/adidas_bots/kisspng-mens-adidas-originals-nmd-r1-cardboard-trainers-5b9abc5ba51f58.0282181815368674196764_ljup0i.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.5,
    numReviews: 53,
    price: 49,
    countInStock: 22,
    sizes: [
      '35.5',
      '36',
      '37 1/3',
      '38',
      '38 2/3',
      '39 1/3',
      '40',
      '40 2/3',
      '42',
      '42 2/3',
      '44',
    ],
    colors: ['#000', '#FF00FF', '#fff'],
    featured: false,
  },
  {
    name: 'adidas blanc low-top',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/kisspng-adidas-shoe-sneakers-clip-art-women-shoes-5ab5851b7d1179.4244234315218455315123_viiegc.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.9,
    numReviews: 121,
    price: 76,
    countInStock: 13,
    sizes: ['35.5', '36', '38', '38 2/3', '40', '40 2/3', '42', '42 2/3', '44'],
    colors: ['#FF00FF', '#fff', '#800080	'],
    featured: false,
  },
  {
    name: 'adidas x Prada Luna Rossa',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/kisspng-adidas-nmd-r1-primeknit-mens-by1912-adidas-nmd-r1-5b9fdc66d3ee36.1366677715372033028681_gtisr1.png',
    brand: 'adidas',
    category: 'women',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.7,
    numReviews: 22,
    price: 39,
    countInStock: 6,
    sizes: ['35.5', '36', '38 2/3', '40', '42'],
    colors: ['#fff'],
    featured: false,
  },
  {
    name: 'adidas x Prada Luna Rossa',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/kisspng-adidas-originals-swift-run-sports-shoes-adidas-tod-5ba1e0e730d5e0.2305695415373355272_d6klow.png',
    brand: 'adidas',
    category: 'children',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.6,
    numReviews: 22,
    price: 39,
    countInStock: 6,
    sizes: ['26.6', '27', '28', '29', '31', '33', '34'],
    colors: ['#FF00FF', '#FFF'],
    featured: false,
  },
  {
    name: 'adidas zx 420',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/kisspng-adidas-originals-skate-shoe-sneakers-adidas-adidas-shoes-5a7919d104d681.1072229915178859050198_lhb9kd.png',
    brand: 'adidas',
    category: 'children',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.2,
    numReviews: 17,
    price: 59,
    countInStock: 12,
    sizes: ['26.6', '27', '28', '29', '30', '31', '31.5', '33', '34'],
    colors: ['#FF00FF', '#FFF', '#00FF00', '#FF0000'],
    featured: false,
  },
  {
    name: 'adidas x 424 arsenal',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926603/my-ecommerce/BOTS/adidas_bots/kisspng-adidas-nmd-r1-primeknit-mens-by1912-adidas-nmd-r1-5b9fdc66d3ee36.1366677715372033028681_gtisr1.png',
    brand: 'adidas',
    category: 'children',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 4.5,
    numReviews: 7,
    price: 49,
    countInStock: 6,
    sizes: ['26.6', '27', '30', '31', '31.5'],
    colors: ['#FFF', '#00FF00'],
    featured: false,
  },
  {
    name: 'adidas wien low-top',
    image:
      'https://res.cloudinary.com/do5rzxmh3/image/upload/v1635926602/my-ecommerce/BOTS/adidas_bots/adidas-shoes-png-26546_xhkmom.png',
    brand: 'adidas',
    category: 'children',
    subCategory: 'boots',
    desc: 'Simplicity, versatility and comfort. Lace up these running-inspired shoes on action-filled days. They are quick to slip on when you are racing out the door. The rubber outsole gives you traction on slippery and uneven surfaces. A Cloudfoam midsole is for a soft feel and all-day cushioning. This product is made with Primegreen, a series of high-performance recycled materials. 50% of the upper is recycled content. No virgin polyester.',
    rating: 3.7,
    numReviews: 12,
    price: 78,
    countInStock: 6,
    sizes: ['27', , '29', '31', '32', '34'],
    colors: ['#FFF', '#00FF00'],
    featured: false,
  },
];
